version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing dependencies"
    
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Pre build"
    
  build:
    on-failure: ABORT
    commands:
      - echo "Building"
    
  post_build:
    on-failure: ABORT
    commands:
      - echo "Post build"
    